name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4']
        sf_version: ['4.4.*', '5.0.*']

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
       
      - name: Install dependencies
        run: composer install
        env:
          COMPOSER_NO_INTERACTION: 1
          SYMFONY_REQUIRE: ${{ matrix.sf_version }}

      - name: Run tests
        run: ./vendor/bin/simple-phpunit
